services:
  - type: web
    name: portfolio-optimizer-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: portfolio-db
          property: connectionString
      - key: REDIS_URL
        value: "redis://localhost:6379"
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: ENVIRONMENT
        value: "production"
      - key: CORS_ORIGINS
        value: "https://portfolio-optimizer.vercel.app,https://portfolio-optimization-dashboard.vercel.app"
      
databases:
  - name: portfolio-db
    databaseName: portfolio_optimization
    user: portfolio_user